# Generated by Django 2.2.5 on 2019-09-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='across_cities',
        ),
        migrations.AddField(
            model_name='route',
            name='trains',
            field=models.ManyToManyField(blank=True, to='trains.Train', verbose_name='Поезда'),
        ),
    ]
