# Generated by Django 2.2.5 on 2019-09-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20190925_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='from_city',
            field=models.CharField(max_length=100, verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_city',
            field=models.CharField(max_length=100, verbose_name='Куда'),
        ),
    ]
